#!/usr/bin/env python3
"""Prove defaults compile native code, even when generated-C compilation is blocked."""
import os
from pathlib import Path
import shutil
import subprocess
import sys
import tempfile

root = Path(__file__).resolve().parents[3]
compiler = Path(sys.argv[1]).resolve()
source = root / "tests/programs/backend_default/main.lucb"

with tempfile.TemporaryDirectory(prefix="base-native-default-") as tmp:
    work = Path(tmp)
    guard = work / "cc"
    guard.write_text("#!/usr/bin/env python3\nimport os, sys\n"
                     "if any(a.endswith('/gen.c') for a in sys.argv[1:]):\n"
                     "    sys.stderr.write('generated C blocked by native-default test\\n')\n"
                     "    sys.exit(97)\n"
                     "os.execv(os.environ['LUCE_REAL_CC'], [os.environ['LUCE_REAL_CC'], *sys.argv[1:]])\n")
    guard.chmod(0o755)
    env = dict(os.environ, LUCE_REAL_CC=shutil.which("cc"), PATH=f"{work}:{os.environ['PATH']}")

    def run(*args, expected=0, guarded=True):
        command = [sys.executable, str(root / "tools/run_case.py"), "--expected", str(expected), "--", *map(str, args)]
        result = subprocess.run(command, cwd=root, env=env if guarded else None, capture_output=True)
        if result.returncode != expected:
            raise SystemExit(f"FAIL {args}: {result.returncode}\n{result.stdout.decode()}{result.stderr.decode()}")
        return result

    exe = work / "program"
    for flags in [[], ["--release"], ["--native"], ["--backend=native"]]:
        run(compiler, "build", source, *flags, "-o", exe)
        assert run(exe).stdout == b"42\n"
    assert b"1 passed" in run(compiler, "test", source).stdout
    run(compiler, "build", source, "--lib", "-o", work / "library")
    assert (work / "library.a").exists()
    run(compiler, "build", source, "--debug", "-o", exe)
    assert run(exe).stdout == b"42\n"

    rejected = run(compiler, "build", source, "--backend=c", "-o", exe, expected=1)
    assert b"generated C blocked" in rejected.stderr
    for flags in [["--backend=c"], ["--backend=c", "--release"]]:
        run(compiler, "build", source, *flags, "-o", exe, guarded=False)
        assert run(exe).stdout == b"42\n"
    assert b"1 passed" in run(compiler, "test", source, "--backend=c", guarded=False).stdout
    run(compiler, "build", source, "--backend=c", "--debug", expected=1)
    for flags, marker in [(["--native", "--emit=c"], b"/* generated by luce-base */"),
                          (["--emit=c", "--native"], b"/* generated by luce-base */"),
                          (["--backend=c", "--emit=asm"], b"lb_main:"),
                          (["--emit=asm", "--backend=c"], b"lb_main:")]:
        output = work / "emission"
        run(compiler, "build", source, *flags, "-o", output)
        assert marker in output.read_bytes()
    run(compiler, "build", source, "--backend=missing", expected=2)
print("ok native defaults: executable, release, tests, archive, DWARF and explicit C comparison")
