/* generated by `luce-base bind` from SDL.h; do not edit */
#include <SDL3/SDL.h>
_Bool luce_SDL_size_mul_check_overflow(size_t a0, size_t a1, size_t *a2) { return SDL_size_mul_check_overflow(a0, a1, a2); }
_Bool luce_SDL_size_add_check_overflow(size_t a0, size_t a1, size_t *a2) { return SDL_size_add_check_overflow(a0, a1, a2); }
Uint16 luce_SDL_Swap16(Uint16 a0) { return SDL_Swap16(a0); }
Uint32 luce_SDL_Swap32(Uint32 a0) { return SDL_Swap32(a0); }
Uint64 luce_SDL_Swap64(Uint64 a0) { return SDL_Swap64(a0); }
float luce_SDL_SwapFloat(float a0) { return SDL_SwapFloat(a0); }
int luce_SDL_MostSignificantBitIndex32(Uint32 a0) { return SDL_MostSignificantBitIndex32(a0); }
_Bool luce_SDL_HasExactlyOneBitSet32(Uint32 a0) { return SDL_HasExactlyOneBitSet32(a0); }
void luce_SDL_RectToFRect(const SDL_Rect *a0, SDL_FRect *a1) { SDL_RectToFRect(a0, a1); }
_Bool luce_SDL_PointInRect(const SDL_Point *a0, const SDL_Rect *a1) { return SDL_PointInRect(a0, a1); }
_Bool luce_SDL_RectEmpty(const SDL_Rect *a0) { return SDL_RectEmpty(a0); }
_Bool luce_SDL_RectsEqual(const SDL_Rect *a0, const SDL_Rect *a1) { return SDL_RectsEqual(a0, a1); }
_Bool luce_SDL_PointInRectFloat(const SDL_FPoint *a0, const SDL_FRect *a1) { return SDL_PointInRectFloat(a0, a1); }
_Bool luce_SDL_RectEmptyFloat(const SDL_FRect *a0) { return SDL_RectEmptyFloat(a0); }
_Bool luce_SDL_RectsEqualEpsilon(const SDL_FRect *a0, const SDL_FRect *a1, float a2) { return SDL_RectsEqualEpsilon(a0, a1, a2); }
_Bool luce_SDL_RectsEqualFloat(const SDL_FRect *a0, const SDL_FRect *a1) { return SDL_RectsEqualFloat(a0, a1); }
