#!/usr/bin/env python3
"""Compile portable triangle shaders; builds use the checked-in SPIR-V words."""
import argparse
from pathlib import Path
import struct
import subprocess
import tempfile

ROOT = Path(__file__).resolve().parents[1] / 'src/std/gpu/vulkan'
parser = argparse.ArgumentParser(description=__doc__)
parser.add_argument('--compiler', default='glslangValidator')
args = parser.parse_args()
lines = ['## Generated by tools/embed_vulkan_shaders.py; Vulkan 1.0 SPIR-V.', '']
with tempfile.TemporaryDirectory(prefix='luce-shader-') as temporary:
    for stage in ('vert', 'frag'):
        output = Path(temporary) / f'{stage}.spv'
        subprocess.run([args.compiler, '-V', '--target-env', 'vulkan1.0',
                        str(ROOT / f'triangle.{stage}'), '-o', str(output)], check=True)
        data = output.read_bytes()
        words = struct.unpack(f'<{len(data) // 4}I', data)
        assert words[0] == 0x07230203
        lines.append(f'var vulkan_{stage}_words: u32[{len(words)}] = [')
        for offset in range(0, len(words), 8):
            lines.append('    ' + ', '.join(f'0x{word:08x}' for word in words[offset:offset + 8]) + ',')
        lines += [']', '']
(ROOT / 'shaders.lucb').write_bytes(('\n'.join(lines)).encode("utf-8"))
