#!/usr/bin/env python3
"""Embed native link requirements declared beside standard-library backends."""
from pathlib import Path
import json
import sys

ROOT = Path(__file__).resolve().parents[1]
rows = set()
for path in sorted((ROOT / 'src/std').rglob('links.json')):
    data = json.loads(path.read_text())
    for requirement in data['requirements']:
        for symbol in requirement['symbols']:
            for kind in ('libraries', 'frameworks'):
                for name in requirement.get(kind, []):
                    rows.add((data['target'], symbol, name, kind == 'frameworks'))
lines = ['## Generated by tools/embed_native_links.py from backend-owned links.json files.',
         'import c', '', 'pub struct Rule:', '    pub let target: str',
         '    pub let symbol: str', '    pub let name: c.str',
         '    pub let framework: bool', '', f'pub let rules: Rule[{len(rows)}] = [']
for target, symbol, name, framework in sorted(rows):
    lines.append(f'    Rule({json.dumps(target)}, {json.dumps(symbol)}, {json.dumps(name)}, {str(framework).lower()}),')
lines.append(']')
text = '\n'.join(lines) + '\n'
output = ROOT / 'src/support/native_link_table.lucb'
if '--check' in sys.argv:
    if not output.exists() or output.read_text() != text:
        raise SystemExit('native link table is stale; run tools/embed_native_links.py')
else:
    output.write_text(text)
    print('wrote src/support/native_link_table.lucb')
