#!/usr/bin/env python3
"""Write src/support/runtime.lucb: the C runtime sources as raw Base text, so the
compiler binary carries everything the generated C needs. With `--check`, write nothing:
exit 1 when the embedded text is not what runtime/ says."""
import pathlib, sys

root = pathlib.Path(__file__).resolve().parent.parent
files = [("header", "lucb_rt.h"), ("source", "lucb_rt.c"), ("start", "start.c")]
out = []
out.append('''#==============================================================================================
#
#   runtime - The C runtime carried inside the compiler
#
#   DESCRIPTION:
#       The generated C includes `lucb_rt.h` and links `lucb_rt.c`; an `answer()` program
#       also links `start.c`. The three files live under `runtime/` and are copied here by
#       `tools/embed_runtime.py` as raw text, so a build needs nothing beside the binary
#       but the host C compiler. Do not edit this file; edit `runtime/` and rerun the tool.
#
#==============================================================================================

''')
for name, file in files:
    text = (root / "runtime" / file).read_text()
    assert '"""' not in text, file
    out.append(f"## The text of `runtime/{file}`.\npub let {name}: str = r\"\"\"{text}\"\"\"\n\n")
target = root / "src" / "support" / "runtime.lucb"
text = "".join(out).rstrip("\n") + "\n"
if "--check" in sys.argv:
    if target.read_text() != text:
        print("src/support/runtime.lucb is not what runtime/ says; run tools/embed_runtime.py")
        sys.exit(1)
    sys.exit(0)
target.write_text(text)
print("wrote src/support/runtime.lucb")
