#!/usr/bin/env python3
"""Write src/support/version.lucb from VERSION, the one place the version lives; build.sh
runs this first, and a release is a VERSION bump, a tag `luce-base-N`, and a push."""
import pathlib

root = pathlib.Path(__file__).resolve().parent.parent
version = (root / "VERSION").read_text().strip()
(root / "src" / "support" / "version.lucb").write_text(
    f"## Generated by tools/embed_version.py from VERSION; edit that file, not this one.\npub let text: str = \"{version}\"\n")
print(f"wrote src/support/version.lucb ({version})")
