#!/usr/bin/env python3
"""Write src/sema/prelude.lucb: the standard modules under src/std/ as Base text the
checker binds before a program's own modules, so the compiler binary carries the whole
standard library. src/std/ORDER lists the modules in binding order. With `--check`, write
nothing: exit 1 when the embedded text is not what src/std/ says, so the gate sees drift."""
import pathlib, sys
from standard_library import module_names, module_source, source_literal

root = pathlib.Path(__file__).resolve().parent.parent
std = root / "src" / "std"
names = module_names(std)
header = '''#==============================================================================================
#
#   prelude - The standard modules, as Base declarations
#
#   DESCRIPTION:
#       Generated by tools/embed_std.py from src/std/; edit those files, not this
#       one. base.md §16.6 names the standard modules; a Base program reaches them with
#       `import` or by their bare names. The checker needs their signatures, and the
#       right place for signatures is Base source. Each module below is a piece of Base
#       text the checker parses and binds before a program's own modules, so `memory`,
#       `io`, `files`, `process`, `thread`, `sync`, `atomic`, `c`, and `luce` are ordinary
#       modules with ordinary declarations, and the backend emits their bodies like any
#       other code. They reach the operating system through `extern` (§17): the C
#       library's own functions, declared here with the types Base gives them. The few
#       things no Base body can express, `atomic.fence`, the `luce` facts, and the C
#       standard streams, the backend supplies.
#
#       The constants that follow are those of the first target, arm64-macos (§19.5);
#       a second target gets its own copy of this module through the per-target
#       modules of §16.4.
#
#==============================================================================================

pub struct Prelude:
    pub var name: str
    pub var text: str

## The modules in binding order (src/std/ORDER): `memory` first because `io` names its
## types, `atomic` before `sync`, whose orderings it declares.
'''
out = [header, f"pub let modules: Prelude[{len(names)}] = [\n"]
for name in names:
    text = module_source(std, name)
    out.append(f'    Prelude(name = "{name}", text = {source_literal(text)}),\n')
out.append("]\n")
target = root / "src" / "sema" / "prelude.lucb"
if "--check" in sys.argv:
    if target.read_text(encoding="utf-8") != "".join(out):
        print("src/sema/prelude.lucb is not what src/std/ says; run tools/embed_std.py")
        sys.exit(1)
    sys.exit(0)
target.write_bytes(("".join(out)).encode("utf-8"))
print(f"wrote src/sema/prelude.lucb ({len(names)} modules)")
