#!/usr/bin/env python3
"""Write src/support/version.lucb from VERSION, the one place the version lives; build.sh
runs this first, and a release is a VERSION bump, a tag `luce-base-N`, and a push. With
`--check`, write nothing: exit 1 when the embedded text is not VERSION."""
import pathlib, sys

root = pathlib.Path(__file__).resolve().parent.parent
version = (root / "VERSION").read_text().strip()
target = root / "src" / "support" / "version.lucb"
text = f"## Generated by tools/embed_version.py from VERSION; edit that file, not this one.\npub let text: str = \"{version}\"\n"
if "--check" in sys.argv:
    if target.read_text() != text:
        print("src/support/version.lucb is not VERSION; run tools/embed_version.py")
        sys.exit(1)
    sys.exit(0)
target.write_text(text)
print(f"wrote src/support/version.lucb ({version})")
