#!/usr/bin/env python3
"""Embed native link requirements declared beside standard-library backends."""
from pathlib import Path
import json
import sys

ROOT = Path(__file__).resolve().parents[1]
rows = set()
for path in sorted((ROOT / 'src/std').rglob('links.json')):
    data = json.loads(path.read_text(encoding="utf-8"))
    # `target` is one name or a list: a Linux backend serves both architectures
    targets = data['target'] if isinstance(data['target'], list) else [data['target']]
    for requirement in data['requirements']:
        for symbol in requirement['symbols']:
            for kind in ('libraries', 'frameworks'):
                for name in requirement.get(kind, []):
                    for target in targets:
                        rows.add((target, symbol, name, kind == 'frameworks'))
lines = ['#==============================================================================================',
         '#',
         '#   native_link_table - Which native symbol pulls in which library',
         '#',
         '#   DESCRIPTION:',
         "#       Generated by tools/embed_native_links.py from the backends' links.json files.",
         '#       Each rule names, for one target, the library or framework a symbol needs.',
         '#',
         '#==============================================================================================',
         '',
         'import c', '',
         '## One link rule: for a target, the library or framework a symbol requires.',
         'pub struct Rule:',
         '    ## The target triple the rule applies to.',
         '    pub let target: str',
         '    ## The symbol whose use requires the library.',
         '    pub let symbol: str',
         '    ## The library or framework name.',
         '    pub let name: c.str',
         '    ## Whether `name` is a macOS framework rather than a plain library.',
         '    pub let framework: bool', '',
         '## Every link rule, across all targets.',
         f'pub let rules: Rule[{len(rows)}] = [']
for target, symbol, name, framework in sorted(rows):
    lines.append(f'    Rule({json.dumps(target)}, {json.dumps(symbol)}, {json.dumps(name)}, {str(framework).lower()}),')
lines.append(']')
text = '\n'.join(lines) + '\n'
output = ROOT / 'src/support/native_link_table.lucb'
if '--check' in sys.argv:
    if not output.exists() or output.read_text(encoding="utf-8") != text:
        raise SystemExit('native link table is stale; run tools/embed_native_links.py')
else:
    output.write_bytes((text).encode("utf-8"))
    print('wrote src/support/native_link_table.lucb')
