#!/usr/bin/env python3
"""Write src/support/version.lucb from VERSION, the one place the version lives; build.sh
runs this first, and a release is a VERSION bump, a tag `luce-base-N`, and a push. With
`--check`, write nothing: exit 1 when the embedded text is not VERSION."""
import pathlib, sys

root = pathlib.Path(__file__).resolve().parent.parent
version = (root / "VERSION").read_text(encoding="utf-8").strip()
target = root / "src" / "support" / "version.lucb"
header = (
    "#==============================================================================================\n"
    "#\n"
    "#   version - The compiler's version string\n"
    "#\n"
    "#   DESCRIPTION:\n"
    "#       Generated by tools/embed_version.py from VERSION; edit that file, not this one.\n"
    "#\n"
    "#==============================================================================================\n"
)
text = header + f"\n## The version of luce-base this binary was built from.\npub let text: str = \"{version}\"\n"
if "--check" in sys.argv:
    if target.read_text(encoding="utf-8") != text:
        print("src/support/version.lucb is not VERSION; run tools/embed_version.py")
        sys.exit(1)
    sys.exit(0)
target.write_bytes((text).encode("utf-8"))
print(f"wrote src/support/version.lucb ({version})")
