#!/usr/bin/env python3
"""Write src/sema/prelude.lucb: the standard modules under src/std/ as Base text the
checker binds before a program's own modules, so the compiler binary carries the whole
standard library. src/std/ORDER lists the modules in binding order."""
import pathlib

root = pathlib.Path(__file__).resolve().parent.parent
std = root / "src" / "std"
names = (std / "ORDER").read_text().split()
header = '''#==============================================================================================
#
#   prelude - The standard modules, as Base declarations
#
#   DESCRIPTION:
#       Generated by tools/embed_std.py from src/std/*.lucb; edit those files, not this
#       one. base.md §16.6 names the standard modules; a Base program reaches them with
#       `import` or by their bare names. The checker needs their signatures, and the
#       right place for signatures is Base source. Each module below is a piece of Base
#       text the checker parses and binds before a program's own modules, so `memory`,
#       `io`, `files`, `process`, `thread`, `sync`, `atomic`, `c`, and `luce` are ordinary
#       modules with ordinary declarations, and the backend emits their bodies like any
#       other code. They reach the operating system through `extern` (§17): the C
#       library's own functions, declared here with the types Base gives them. The few
#       things no Base body can express, `atomic.fence`, the `luce` facts, and the C
#       standard streams, the backend supplies.
#
#       The constants that follow are those of the first target, arm64-macos (§19.5);
#       a second target gets its own copy of this module through the per-target
#       modules of §16.4.
#
#==============================================================================================

pub struct Prelude:
    pub var name: str
    pub var text: str

## The modules in binding order (src/std/ORDER): `memory` first because `io` names its
## types, `atomic` before `sync`, whose orderings it declares.
'''
out = [header, f"pub let modules: Prelude[{len(names)}] = [\n"]
for name in names:
    text = (std / f"{name}.lucb").read_text()
    assert '"""' not in text, name
    out.append(f'    Prelude(name = "{name}", text = """\n{text}"""),\n')
out.append("]\n")
(root / "src" / "sema" / "prelude.lucb").write_text("".join(out))
print(f"wrote src/sema/prelude.lucb ({len(names)} modules)")
