#!/usr/bin/env python3
"""Write src/support/runtime.lucb: the C runtime sources as raw Base text, so the
compiler binary carries everything the generated C needs."""
import pathlib

root = pathlib.Path(__file__).resolve().parent.parent
files = [("header", "lucb_rt.h"), ("source", "lucb_rt.c"), ("start", "start.c")]
out = []
out.append('''#==============================================================================================
#
#   runtime - The C runtime carried inside the compiler
#
#   DESCRIPTION:
#       The generated C includes `lucb_rt.h` and links `lucb_rt.c`; an `answer()` program
#       also links `start.c`. The three files live under `runtime/` and are copied here by
#       `tools/embed_runtime.py` as raw text, so a build needs nothing beside the binary
#       but the host C compiler. Do not edit this file; edit `runtime/` and rerun the tool.
#
#==============================================================================================

''')
for name, file in files:
    text = (root / "runtime" / file).read_text()
    assert '"""' not in text, file
    out.append(f"## The text of `runtime/{file}`.\npub let {name}: str = r\"\"\"{text}\"\"\"\n\n")
(root / "src" / "support" / "runtime.lucb").write_text("".join(out).rstrip("\n") + "\n")
print("wrote src/support/runtime.lucb")
