#!/usr/bin/env python3
"""Write docs/LIBRARY.md: the standard library's public surface, read from src/std/.
Every `pub` declaration appears with the doc comment (`##` lines) written above it, so the
reference is the source's own words and never drifts from it. Run after editing src/std;
with `--check`, write nothing and exit 1 when docs/LIBRARY.md is not what the source says."""
import pathlib, re, sys
from standard_library import module_names, module_source

root = pathlib.Path(__file__).resolve().parent.parent
std = root / "src" / "std"
names = module_names(std)
skip = {"core", "luce", "debug", "testing", "windows_abi", "windows_text"}   # the compiler's own, not a program's

def comment_block(lines, i):
    """The `##` lines ending just before line i, as one paragraph."""
    j = i
    while j > 0 and lines[j - 1].strip().startswith("##"):
        j -= 1
    text = " ".join(l.strip()[2:].strip() for l in lines[j:i])
    return text.strip()

def render(name):
    lines = module_source(std, name).split("\n")
    out = [f"## `{name}`\n"]
    head = []
    for l in lines:
        if l.startswith("##"):
            head.append(l[2:].strip())
        elif l.strip() == "":
            continue
        else:
            break
    if head:
        out.append(" ".join(head) + "\n")
    i = 0
    while i < len(lines):
        l = lines[i]
        m = re.match(r"pub (struct|interface|union|enum) (\w+)(.*):$", l)
        if m:
            kind, ident, rest = m.groups()
            doc = comment_block(lines, i)
            out.append(f"### `{ident}`" + (f" ({kind}{rest.strip()})" if rest.strip() else f" ({kind})") + "\n")
            if doc:
                out.append(doc + "\n")
            members = []
            j = i + 1
            while j < len(lines) and (lines[j].startswith("    ") or lines[j].strip() == ""):
                s = lines[j].strip()
                mm = re.match(r"pub (static func|mutating func|func|var|let) (.*)", s)
                if mm:
                    d = comment_block(lines, j)
                    members.append(f"- `{mm.group(1)} {mm.group(2).rstrip(':')}`" + (f" — {d}" if d else ""))
                j += 1
            if members:
                out.append("\n".join(members) + "\n")
            i = j
            continue
        m = re.match(r"pub (func|let|var|type) (.*)", l)
        if m:
            doc = comment_block(lines, i)
            sig = m.group(2).rstrip(":")
            out.append(f"- `{m.group(1)} {sig}`" + (f" — {doc}" if doc else "") + "\n")
        i += 1
    return "\n".join(out)

doc = ["# The Luce Base standard library\n",
       "Generated by `tools/library_reference.py` from `src/std/`; the source is the reference. "
       "A module is reached with `import name` and used as `name.thing`, or `from name import thing` for its bare name (§16.6). "
       "Everything here is Base over `extern` declarations of system libraries; where a constant or a layout differs by target it is a branch on the `platform` module (§19.5), checked by `tests/platform` and the corresponding platform-specific program tests.\n"]
for n in names:
    if n in skip or n == "c":
        continue
    doc.append(render(n))
doc.append("## `c`\n\nThe C types (`c.int`, `c.long`, `c.char`, `c.str`, `c.va_list`, …) and the standard streams `c.stdin()`, `c.stdout()`, `c.stderr()` (§5.2, §17).\n")
target = root / "docs" / "LIBRARY.md"
text = "\n".join(doc)
if "--check" in sys.argv:
    if target.read_text(encoding="utf-8") != text:
        print("docs/LIBRARY.md is not what src/std/ says; run tools/library_reference.py")
        sys.exit(1)
    sys.exit(0)
target.write_bytes((text).encode("utf-8"))
print("wrote docs/LIBRARY.md")
