/* generated by `luce-base bind` from sample.h; do not edit */
#include "sample.h"
int luce_sample_twice(int a0) { return sample_twice(a0); }
int luce_SAMPLE_SQUARE(int a0) { return SAMPLE_SQUARE(a0); }
